### ISSUE TITLE
Can't seem to update content-security-policy in lambaEdge function.

### ISSUE THREAD

**Issue by Atticus29** [aws-samples/amazon-cloudfront-secure-static-site#20]
I'm getting some errors on my page that suggest that I need to add some urls to my content-security-policy directives:

<img width="1440" alt="Screen Shot 2020-08-29 at 8 01 15 PM" src="https://user-images.githubusercontent.com/2775448/91650288-690dd500-ea32-11ea-98e0-2f004d7fd87c.png">

So, I did just that:
```
`'use strict';
exports.handler = (event, context, callback) => {

    //Get contents of response
    const response = event.Records[0].cf.response;
    const headers = response.headers;

//Set new headers 
 headers['strict-transport-security'] = [{key: 'Strict-Transport-Security', value: 'max-age=63072000; includeSubdomains; preload'}]; 
 headers['content-security-policy'] = [{key: 'Content-Security-Policy', value: "frame-src https://js.stripe.com https://hooks.stripe.com; connect-src https://api.stripe.com; default-src 'none'; img-src 'self'; script-src 'self'; style-src 'self' https://js.stripe.com;style-src-elem https://fonts.googleapis.com/icon?family=Material+Icons; object-src 'none'"}]; 
 headers['x-content-type-options'] = [{key: 'X-Content-Type-Options', value: 'nosniff'}]; 
 headers['x-frame-options'] = [{key: 'X-Frame-Options', value: 'DENY'}]; 
 headers['x-xss-protection'] = [{key: 'X-XSS-Protection', value: '1; mode=block'}]; 
 headers['referrer-policy'] = [{key: 'Referrer-Policy', value: 'same-origin'}]; 
    
    //Return modified response
    callback(null, response);
};
```

I checked back after saving the changes to the lambda function, and viewing the header of the page suggests that the changes were not propagated:
<img width="1440" alt="Screen Shot 2020-08-29 at 8 05 10 PM" src="https://user-images.githubusercontent.com/2775448/91650328-f4876600-ea32-11ea-9e7f-6a5561b5713f.png">

My first thought was that maybe it was a caching issues, so I invalidated all of the files in my CDN and then both published a new version of the lambda function and deployed it using an existing cloudfront trigger:
<img width="1440" alt="Screen Shot 2020-08-29 at 8 15 08 PM" src="https://user-images.githubusercontent.com/2775448/91650436-6b712e80-ea34-11ea-835b-fefe1c5e6d43.png">

I'm a little bit out of my depth here and am hopeful that, if not germane to the contents of the repo., you might be able to suggest a good avenue for troubleshooting.

**Comment by ConnorKirk** [comment]
Hi Mark,

Thanks for raising an issue. I am sorry that you are having trouble updating the content security policy of the Lambda@Edge function. 

My understanding is that:
* You would like to update the Content Security Policy of the Lambda@Edge function deployed in this template
* You made changes to the function, but this the headers of the site did not update.
* You invalidated the cache of the CloudFront distribution, but this did not help
* You have published a new version of the Lambda@Edge function, and deployed it with the existing trigger. The headers had still not updated.


I believe the issue lies somewhere in the configuration of the Lambda@Edge function and CloudFront, rather than this solution itself.

I have a few thoughts to try and assist debugging:
* After you make updates to a CloudFront distribution, like adding triggers, you must wait for the changes to propagate to edge locations before the functions you've specified in the triggers will work. If you haven't already, it might be worth trying the function again now to see if this is the case.

* You may have already come across this document. It explains the steps to update a Lambda@Edge function. Could you read through it and ensure you completed every step when you made your change.
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-edge-edit-function.html

Could you try these two steps? If that doesn't work we can try something else.

**Comment by ConnorKirk** [comment]
Hi Mark, 
I've not heard back. I am hoping this is because you've resolved the issue 👍 
I intend to close this issue in the next few days unless I hear back from you.

Thanks again for raising the issue. I intend to add documentation to better explain how to update the CSP.

**Comment by Atticus29** [comment]
Hi @ConnorKirk ! I'm a bit of a weekend warrior with this these days. I will let you know asap whether this works. Very likely by Saturday. Apologies for the slow pace!

**Comment by ConnorKirk** [comment]
No problem Mark :)
I will check back with this next week. No rush

**Comment by Atticus29** [comment]
Alright! @ConnorKirk! Even though I don't yet have my page working, it does indeed seem just that I was not patient enough. I'm getting new and exciting console errors now downstream of this. 
Thank you for the tip! I hadn't appreciated that the lambda edge functions propagate at a different rate from the CDN more broadly. Is there any analogous thing that I can do for the lambda edge functions to invalidating a CDN, in an effort to accelerate things?

**Comment by ConnorKirk** [comment]
I'm pleased it is fixed, Mark 👍 

Unfortunately there isn't an equivalent to cache invalidation for Lambda@Edge functions.

Thanks for raising an issue. I intend to close this issue, but you're welcome to reopen it if I have missed anything.
